# Generated by Django 5.2.8 on 2025-12-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="is_published",
            field=models.BooleanField(
                default=False,
                help_text="Подтвердите публикацию",
                verbose_name="Подтверждение публикации",
            ),
        ),
    ]
