# Generated by Django 5.2.8 on 2025-11-24 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Категория", "verbose_name_plural": "Категории"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Продукт", "verbose_name_plural": "Продукты"},
        ),
        migrations.AlterField(
            model_name="product",
            name="photo",
            field=models.ImageField(
                upload_to="catalog/photo/", verbose_name="Фотография"
            ),
        ),
    ]
