# Generated by Django 5.2.8 on 2025-12-13 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="publication_status",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
