# Generated by Django 5.2.8 on 2025-12-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_publication_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="publication_status",
            field=models.BooleanField(default=False),
        ),
    ]
