# Generated by Django 5.2.8 on 2025-12-14 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_alter_product_publication_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="owner",
            field=models.ForeignKey(
                default=3,
                help_text="Укажите владельца",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="product",
            name="publication_status",
            field=models.BooleanField(
                default=False, verbose_name="Флаг для публикации"
            ),
        ),
    ]
